### ISSUE TITLE
Reorder primary attribute thingies

### ISSUE THREAD

**Issue by whisperity** [Total-RP/Total-RP-3#378] opened 2019-12-26 21:13 UTC
**Describe the solution you'd like**
Perhaps same as in the solution for #51, but for the primary characteristics. Currently, the only way is to manually edit the save file.

**Comment by Solanya** [comment] 2019-12-26 22:46
Sounds like a duplicate of #312 ?

**Closed** 2020-05-13 17:00 UTC
