### ISSUE TITLE
Set companion profile per character

### ISSUE THREAD

**Issue by Solanya** [Total-RP/Total-RP-3#419] opened 2020-09-08 12:16 UTC
> Each of my characters have their own special pet and mount. For example, my Monk uses Squeakers as his special mount. I've written backstories for all of them and how they met the character, and i bound them to the pet/mount. However, i was wondering if there was a way to bind that to a certain character only. Like my Dreadwake is bound to my mage character as that's his special mount (Like Jania Proudmoore) but I'll also use my Dreadwake on other characters when applicable (if i'm RP'ing as a pirate mainly) but the backstory of the mount will confuse others, as it's written for a different character.

Currently profiles are set account-wide but there could be a system where you only link a companion profile when a specific character profile is active.

**Comment by Meorawr** [comment] 2023-05-28 19:58
Duplicate of #55.

**Closed by Meorawr** 2023-05-28 19:58 UTC
