### ISSUE TITLE
New error with the new patch in.

### ISSUE THREAD

**Issue by NanerFish** [Total-RP/Total-RP-3#761] opened 2023-05-04 01:50 UTC
## Describe the issue
Error in a lua code about a Color thing keeps coming up.

## Expected behaviour
Nothing, no Lua Errors

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Log-in
2. Have add-on
3. When someone chats

## Additional files
Message: Interface/AddOns/totalRP3/Core/Color.lua:223: attempted to create a color from an invalid color markup string
Time: Wed May  3 20:43:22 2023
Count: 1
Stack: Interface/AddOns/totalRP3/Core/Color.lua:223: attempted to create a color from an invalid color markup string
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/totalRP3/Core/Color.lua"]:223: in function `CreateColorFromHexMarkup'
[string "@Interface/AddOns/totalRP3/Modules/ChatFrame/Prat.lua"]:60: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Prat-3.0/addon/addon.lua"]:696: in function <Interface/AddOns/Prat-3.0/addon/addon.lua:611>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/ChatFrame.lua"]:3156: in function `ChatFrame_OnEvent'
[string "*FloatingChatFrame.xml:663_OnEvent"]:1: in function <[string "*FloatingChatFrame.xml:663_OnEvent"]:1>

Locals: (*temporary) = "attempted to create a color from an invalid color markup string"

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Meorawr** [comment] 2023-05-04 01:51
Duplicate of #756 - will be fixed in the next update.

**Closed by Meorawr** 2023-05-04 01:51 UTC
